<a href="https://colab.research.google.com/github/sarah-abeer/Transaction-Fraud-Detection-Model/blob/main/Transaction_Fraud_Detection_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the diabetes dataset to a pandas DataFrame
credit_card_data=pd.read_csv('/content/Fraud.csv')

In [ ]:
credit_card_data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [ ]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791143 entries, 0 to 791142
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   step            791143 non-null  int64
 1   type            791143 non-null  object
 2   amount          791143 non-null  float64
 3   nameOrig        791143 non-null  object
 4   oldbalanceOrg   791143 non-null  float64
 5   newbalanceOrig  791142 non-null  float64
 6   nameDest        791142 non-null  object
 7   oldbalanceDest  791142 non-null  float64
 8   newbalanceDest  791142 non-null  float64
 9   isFraud         791142 non-null  float64
 10  isFlaggedFraud  791142 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 66.4+ MB

In [ ]:
#distribution of legit transaction & fraudulent transaction
credit_card_data['isFraud'].value_counts()

isFraud
0.0    790684
1.0       458
Name: count, dtype: int64

0--> Normal Transaction
1-->Fraudlent Transaction

In [ ]:
#seprating the data for analysis
legit=credit_card_data[credit_card_data.isFraud==0]
fraud=credit_card_data[credit_card_data.isFraud==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(790684, 11)
(458, 11)

Under-Sampling

Build a sample dataset containing similar distribution and Fraudulent Transaction

Number of Fraudulent Transaction--> 458

In [ ]:
legit_sample= legit.sample(n=458)

Concatenating two DataFrames

In [ ]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
495281,20,PAYMENT,3306.71,C1105662112,0.00,0.00,M110744204,0.00,0.00,0.0,0.0
519485,20,CASH_IN,108039.32,C1485484885,93131.00,201170.32,C1103647694,476083.97,368044.65,0.0,0.0
401200,18,CASH_IN,2997.27,C1002939631,397643.38,400640.65,C309855152,468248.17,70054.43,0.0,0.0
399571,18,PAYMENT,32916.82,C21206288,538524.27,505607.45,M1691336926,0.00,0.00,0.0,0.0
99231,10,CASH_OUT,86939.12,C1896653173,14122.00,0.00,C1830915224,0.00,86939.12,0.0,0.0

In [ ]:
new_dataset['isFraud'].value_counts

isFraud
0.0    458
1.0    458
Name: count, dtype: int64